### PR TITLE
Ensure pending test title is correctly identified

### PR DESCRIPTION
**Pull request by georgecrawford**

### CODE REVIEW

**Comment by christian-bromann** [comment]
Was this actually causing any problems? Don't really see the advantage of this change.

**Comment by georgecrawford** [comment]
Mocha tests with `skip` get called with a single argument, `specTitle`. If we indiscriminately `pop` or `shift` the arguments array to find a function, we lose this argument, and the resulting `specTitle` is undefined.

Incidentally, this method seems very bound to Mocha, so we might need to move some of this logic into the Mocha adapter. But that can wait.

**Comment by georgecrawford** [comment]
Tests for `wdio-mocha-framework` now pass against this PR.

**Comment by christian-bromann** [comment]
:+1:

**Pull request merged**
