### PR TITLE
Fix error in addCommand method

### PR DESCRIPTION
**Pull request by KOPTE3**
Hello!

This pull request fixes a bug [#1539](https://github.com/webdriverio/webdriverio/issues/1539) in webdriverio.

I wrote _tests_ for this bug and check the corrected version on my project and I ran integration tests in `wdio-mocha-framework`. Everything works correctly, and it's cool :)

Can you please accept this pull request, update the `wdio-sync` package and update the version of `wdio-sync` in [`wdio-mocha-framework`](https://github.com/webdriverio/wdio-mocha-framework/blob/master/package.json#L42)?

### CODE REVIEW

**Comment by KOPTE3** [comment]
I also found that these fixes solve issue [#1796](https://github.com/webdriverio/webdriverio/issues/1796) in `webdriverio`. Keep this in mind ;)

**Comment by christian-bromann** [comment]
> Keep this in mind ;)

I am sure I tried to implement it that way but it was not working for some reasons. Thanks for the PR. I will have to take a closer look tho.

**Comment by monolithed** [comment]
@christian-bromann, hi! Is there anything we can do to speed the merge process along?

**Comment by christian-bromann** [comment]
Merging, even though I am afraid I tried it this way and it caused something else to break.

**Pull request merged**
